/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.event.KeyEvent;
import method.method_barang;

/**
 *
 * @author Muhammad Rydwan
 */
public class barang extends javax.swing.JFrame {

    /**
     * Creates new form barang
     */
    public barang() {
        initComponents();
        this.jtkode.setEnabled(false);
        new method_barang().kunci(this);
        new method_barang().tampil_data(this);
        new method_barang().bersih(this);
        new method_barang().kd_oto(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtkode = new javax.swing.JTextField();
        jtmerk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jttipe = new javax.swing.JTextField();
        jtram = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtprosesor = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtvga = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtstorage = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtbaterai = new javax.swing.JTextField();
        jdtahunrilis = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jtharga = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtstok = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jtcari = new javax.swing.JTextField();
        jccari = new javax.swing.JComboBox<>();
        jbbatal = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbsimpan = new javax.swing.JButton();
        jbubah = new javax.swing.JButton();
        jbhapus = new javax.swing.JButton();
        jbtambah = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel10.setText("Manajemen Barang");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Merk");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jtkode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtkode.setText("jTextField1");
        jtkode.setNextFocusableComponent(jtmerk);
        getContentPane().add(jtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 126, -1));

        jtmerk.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtmerk.setText("jTextField5");
        jtmerk.setNextFocusableComponent(jttipe);
        getContentPane().add(jtmerk, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 230, -1));

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 1110, 360));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Kode");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Tipe");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jttipe.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jttipe.setText("jTextField5");
        jttipe.setNextFocusableComponent(jtram);
        getContentPane().add(jttipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 230, -1));

        jtram.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtram.setText("jTextField5");
        jtram.setNextFocusableComponent(jtprosesor);
        getContentPane().add(jtram, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 230, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setText("RAM");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setText("Prosesor");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jtprosesor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtprosesor.setText("jTextField5");
        jtprosesor.setNextFocusableComponent(jtvga);
        getContentPane().add(jtprosesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 230, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel16.setText("VGA");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jtvga.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtvga.setText("jTextField5");
        jtvga.setNextFocusableComponent(jtstorage);
        getContentPane().add(jtvga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 230, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("Storage");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        jtstorage.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtstorage.setText("jTextField5");
        jtstorage.setNextFocusableComponent(jtbaterai);
        getContentPane().add(jtstorage, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 150, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel18.setText("Tahun Rilis");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jtbaterai.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtbaterai.setText("jTextField5");
        jtbaterai.setNextFocusableComponent(jdtahunrilis);
        getContentPane().add(jtbaterai, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 150, -1));

        jdtahunrilis.setNextFocusableComponent(jtharga);
        getContentPane().add(jdtahunrilis, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 160, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel19.setText("Baterai");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        jtharga.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtharga.setText("jTextField5");
        jtharga.setNextFocusableComponent(jtstok);
        jtharga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jthargaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jthargaKeyTyped(evt);
            }
        });
        getContentPane().add(jtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 210, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel20.setText("Harga");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel21.setText("Stok");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        jtstok.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtstok.setText("jTextField5");
        jtstok.setNextFocusableComponent(jbsimpan);
        jtstok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtstokKeyTyped(evt);
            }
        });
        getContentPane().add(jtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 140, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel22.setText("Cari");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, -1, -1));

        jtcari.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcariActionPerformed(evt);
            }
        });
        getContentPane().add(jtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 290, 210, -1));

        jccari.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jccari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--PILIHAN--", "Kode", "Merk", "Tipe", "RAM", "Prosesor", "VGA", "Storage", "Baterai", "Tahun Rilis", "Harga", "Stok" }));
        getContentPane().add(jccari, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 130, -1));

        jbbatal.setBackground(new java.awt.Color(22, 167, 204));
        jbbatal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbbatal.setForeground(new java.awt.Color(255, 255, 255));
        jbbatal.setText("Batal");
        jbbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbatalActionPerformed(evt);
            }
        });
        getContentPane().add(jbbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 90, 30));

        jButton2.setBackground(new java.awt.Color(22, 167, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 90, 30));

        jbsimpan.setBackground(new java.awt.Color(93, 194, 219));
        jbsimpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbsimpan.setForeground(new java.awt.Color(255, 255, 255));
        jbsimpan.setText("Simpan");
        jbsimpan.setNextFocusableComponent(jtmerk);
        jbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jbsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 90, 40));

        jbubah.setBackground(new java.awt.Color(93, 194, 219));
        jbubah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbubah.setForeground(new java.awt.Color(255, 255, 255));
        jbubah.setText("Ubah");
        jbubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbubahActionPerformed(evt);
            }
        });
        getContentPane().add(jbubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, 90, 40));

        jbhapus.setBackground(new java.awt.Color(93, 194, 219));
        jbhapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbhapus.setForeground(new java.awt.Color(255, 51, 51));
        jbhapus.setText("Hapus");
        jbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhapusActionPerformed(evt);
            }
        });
        getContentPane().add(jbhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 210, 90, 40));

        jbtambah.setBackground(new java.awt.Color(22, 167, 204));
        jbtambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtambah.setForeground(new java.awt.Color(255, 255, 255));
        jbtambah.setText("Tambah");
        jbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtambahActionPerformed(evt);
            }
        });
        getContentPane().add(jbtambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 90, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/bg-pattern-barang.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtambahActionPerformed
        // TODO add your handling code here:
        new method_barang().buka_kunci(this);
        new method_barang().kd_oto(this);
    }//GEN-LAST:event_jbtambahActionPerformed

    private void jbbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbatalActionPerformed
        // TODO add your handling code here:
        new method_barang().kunci(this);
        new method_barang().bersih(this);
        new method_barang().kd_oto(this);
        this.jtmerk.requestFocus();
    }//GEN-LAST:event_jbbatalActionPerformed

    private void jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMouseClicked
        // TODO add your handling code here:
        new method_barang().klik_table(this);
    }//GEN-LAST:event_jtableMouseClicked

    private void jbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsimpanActionPerformed
        // TODO add your handling code here:
        new method_barang().simpan(this);
    }//GEN-LAST:event_jbsimpanActionPerformed

    private void jbubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbubahActionPerformed
        // TODO add your handling code here:
        new method_barang().ubah(this);
    }//GEN-LAST:event_jbubahActionPerformed

    private void jbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhapusActionPerformed
        // TODO add your handling code here:
        new method_barang().hapus(this);
    }//GEN-LAST:event_jbhapusActionPerformed

    private void jthargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jthargaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jthargaKeyPressed

    private void jthargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jthargaKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!( (karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) )){
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jthargaKeyTyped

    private void jtstokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtstokKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if ( !( (karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)  )){
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jtstokKeyTyped

    private void jtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcariActionPerformed
        // TODO add your handling code here:
        new method_barang().cari_data(this);
    }//GEN-LAST:event_jtcariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbbatal;
    public javax.swing.JButton jbhapus;
    public javax.swing.JButton jbsimpan;
    public javax.swing.JButton jbtambah;
    public javax.swing.JButton jbubah;
    public javax.swing.JComboBox<String> jccari;
    public com.toedter.calendar.JDateChooser jdtahunrilis;
    public javax.swing.JTable jtable;
    public javax.swing.JTextField jtbaterai;
    public javax.swing.JTextField jtcari;
    public javax.swing.JTextField jtharga;
    public javax.swing.JTextField jtkode;
    public javax.swing.JTextField jtmerk;
    public javax.swing.JTextField jtprosesor;
    public javax.swing.JTextField jtram;
    public javax.swing.JTextField jtstok;
    public javax.swing.JTextField jtstorage;
    public javax.swing.JTextField jttipe;
    public javax.swing.JTextField jtvga;
    // End of variables declaration//GEN-END:variables
}
