/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import form_detail.detail_barang;
import form_tabel.form_tabel_barang;
import form_tabel.form_tabel_pelanggan;
import java.awt.event.KeyEvent;

import method.method_daftar_cicilan;


/**
 *
 * @author Muhammad Rydwan
 */
public class daftar_cicilan extends javax.swing.JFrame {

//    public detail_barang detailBarang = null;
    public detail_barang detailBarang = new detail_barang();
    /**
     * Creates new form uang_muka
     */
    public daftar_cicilan() {
        initComponents();
        this.jtkode.setEnabled(false);
        new method_daftar_cicilan().bersih(this);
        new method_daftar_cicilan().kunci(this);
        new method_daftar_cicilan().tampil_data(this);
        new method_daftar_cicilan().kd_oto(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jtcari = new javax.swing.JTextField();
        jccari = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jbsimpan = new javax.swing.JButton();
        jbubah = new javax.swing.JButton();
        jbhapus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtkode = new javax.swing.JTextField();
        jbcaripelanggan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtnamapelanggan = new javax.swing.JTextField();
        jtnik = new javax.swing.JTextField();
        jtkodebarang = new javax.swing.JTextField();
        jbcaribarang = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jtnamabarang = new javax.swing.JTextField();
        jthargabarang = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtsisaharga = new javax.swing.JTextField();
        jtuangmuka = new javax.swing.JTextField();
        jtlamanagsuran = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtangsuran = new javax.swing.JTextField();
        jbtambah = new javax.swing.JButton();
        jbbatal = new javax.swing.JButton();
        jdtanggaldaftar = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jcstatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 700));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel10.setText("Mulai Kredit");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel22.setText("Cari");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jtcari.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcariActionPerformed(evt);
            }
        });
        getContentPane().add(jtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 210, -1));

        jccari.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jccari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--PILIHAN--", "Kode", "Nama", "Merk", "Tipe", "Uang Muka", "Sisa Harga", "Lama Angsuran", "Angsuran", "Tanggal Daftar" }));
        getContentPane().add(jccari, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 130, -1));

        jButton2.setBackground(new java.awt.Color(184, 47, 32));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 90, 30));

        jbsimpan.setBackground(new java.awt.Color(184, 47, 32));
        jbsimpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbsimpan.setForeground(new java.awt.Color(255, 255, 255));
        jbsimpan.setText("Simpan");
        jbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jbsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 90, 40));

        jbubah.setBackground(new java.awt.Color(184, 47, 32));
        jbubah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbubah.setForeground(new java.awt.Color(255, 255, 255));
        jbubah.setText("Ubah");
        jbubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbubahActionPerformed(evt);
            }
        });
        getContentPane().add(jbubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, 90, 40));

        jbhapus.setBackground(new java.awt.Color(184, 47, 32));
        jbhapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbhapus.setForeground(new java.awt.Color(255, 255, 255));
        jbhapus.setText("Hapus");
        jbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhapusActionPerformed(evt);
            }
        });
        getContentPane().add(jbhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 280, 90, 40));

        jPanel2.setBackground(new java.awt.Color(219, 235, 222));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Kode Cicilan");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jtkode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtkode.setText("jTextField1");
        jtkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtkodeActionPerformed(evt);
            }
        });
        jPanel2.add(jtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 170, -1));

        jbcaripelanggan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbcaripelanggan.setText("Cari Pelanggan");
        jbcaripelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcaripelangganActionPerformed(evt);
            }
        });
        jPanel2.add(jbcaripelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("NIK");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Nama");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jtnamapelanggan.setEditable(false);
        jtnamapelanggan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtnamapelanggan.setText("jTextField5");
        jPanel2.add(jtnamapelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 230, -1));

        jtnik.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtnik.setText("jTextField5");
        jPanel2.add(jtnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 230, -1));

        jtkodebarang.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtkodebarang.setText("jTextField5");
        jPanel2.add(jtkodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 230, -1));

        jbcaribarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbcaribarang.setText("Cari Barang");
        jbcaribarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcaribarangActionPerformed(evt);
            }
        });
        jPanel2.add(jbcaribarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel14.setText("Kode Barang");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel15.setText("Nama Barang");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel16.setText("Harga Barang");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jtnamabarang.setEditable(false);
        jtnamabarang.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtnamabarang.setText("jTextField5");
        jPanel2.add(jtnamabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 230, -1));

        jthargabarang.setEditable(false);
        jthargabarang.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jthargabarang.setText("jTextField5");
        jPanel2.add(jthargabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 200, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("Uang Muka");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel19.setText("Sisa Harga");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, -1));

        jtsisaharga.setEditable(false);
        jtsisaharga.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtsisaharga.setText("jTextField5");
        jPanel2.add(jtsisaharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 190, -1));

        jtuangmuka.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtuangmuka.setText("jTextField5");
        jtuangmuka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtuangmukaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtuangmukaKeyTyped(evt);
            }
        });
        jPanel2.add(jtuangmuka, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 200, -1));

        jtlamanagsuran.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtlamanagsuran.setText("jTextField5");
        jtlamanagsuran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtlamanagsuranKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtlamanagsuranKeyTyped(evt);
            }
        });
        jPanel2.add(jtlamanagsuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 190, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel20.setText("Lama Angsuran");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel21.setText("Status");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, -1, -1));

        jtangsuran.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtangsuran.setText("jTextField5");
        jtangsuran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtangsuranKeyTyped(evt);
            }
        });
        jPanel2.add(jtangsuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 90, 190, -1));

        jbtambah.setBackground(new java.awt.Color(184, 47, 32));
        jbtambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtambah.setForeground(new java.awt.Color(255, 255, 255));
        jbtambah.setText("Tambah");
        jbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtambahActionPerformed(evt);
            }
        });
        jPanel2.add(jbtambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 30));

        jbbatal.setBackground(new java.awt.Color(184, 47, 32));
        jbbatal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbbatal.setForeground(new java.awt.Color(255, 255, 255));
        jbbatal.setText("Batal");
        jbbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbatalActionPerformed(evt);
            }
        });
        jPanel2.add(jbbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 90, 30));

        jdtanggaldaftar.setPreferredSize(new java.awt.Dimension(91, 10));
        jPanel2.add(jdtanggaldaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 120, 170, 25));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel23.setText("Angsuran");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel18.setText("Rp.");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel24.setText("Rp.");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel25.setText("Rp.");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel26.setText("Rp.");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel27.setText("Tanggal Daftar");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, -1, -1));

        jcstatus.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jcstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BELUM LUNAS", "LUNAS" }));
        jPanel2.add(jcstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1130, 190));

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 1120, 340));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/bg-pattern-cicilan.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtlamanagsuranKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtlamanagsuranKeyPressed
       if (evt.getKeyChar() == KeyEvent.VK_ENTER){
           this.jtangsuran.requestFocus();
       }
    }//GEN-LAST:event_jtlamanagsuranKeyPressed

    private void jtlamanagsuranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtlamanagsuranKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtlamanagsuranKeyTyped

    private void jtangsuranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtangsuranKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
//        if ( !( (karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)  )){
//            evt.consume();
//            getToolkit().beep();
//        }
    }//GEN-LAST:event_jtangsuranKeyTyped

    private void jtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcariActionPerformed
        // TODO add your handling code here:
        new method_daftar_cicilan().cari_data(this);
    }//GEN-LAST:event_jtcariActionPerformed

    private void jbbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbatalActionPerformed
        // TODO add your handling code here:
        new method_daftar_cicilan().kunci(this);
        new method_daftar_cicilan().bersih(this);
        new method_daftar_cicilan().kd_oto(this);

    }//GEN-LAST:event_jbbatalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsimpanActionPerformed
        // TODO add your handling code here:
        new method_daftar_cicilan().simpan(this);
    }//GEN-LAST:event_jbsimpanActionPerformed

    private void jbubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbubahActionPerformed
        // TODO add your handling code here:
        new method_daftar_cicilan().ubah(this);
    }//GEN-LAST:event_jbubahActionPerformed

    private void jbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhapusActionPerformed
        // TODO add your handling code here:
        new method_daftar_cicilan().hapus(this);
    }//GEN-LAST:event_jbhapusActionPerformed

    private void jbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtambahActionPerformed
        // TODO add your handling code here:
        new method_daftar_cicilan().buka_kunci(this);
        new method_daftar_cicilan().kd_oto(this);
    }//GEN-LAST:event_jbtambahActionPerformed

    private void jbcaribarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcaribarangActionPerformed
        // TODO add your handling code here:
//        detail_barang detail_barang = new detail_barang();
//        detail_barang.daftar_cicilan = this;
//        new form_tabel_barang().setVisible(true);

        form_tabel_barang formTabelBarang = new form_tabel_barang();
        formTabelBarang.daftarCicilan = this;
        formTabelBarang.setVisible(true);
    }//GEN-LAST:event_jbcaribarangActionPerformed

    private void jbcaripelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcaripelangganActionPerformed
        // TODO add your handling code here:
          form_tabel_pelanggan formTabelPelanggan = new form_tabel_pelanggan();
          formTabelPelanggan.daftarCicilan = this;
          formTabelPelanggan.setVisible(true);
    }//GEN-LAST:event_jbcaripelangganActionPerformed

    private void jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMouseClicked
        // TODO add your handling code here:
        new method_daftar_cicilan().klik_table(this);
    }//GEN-LAST:event_jtableMouseClicked

    private void jtuangmukaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtuangmukaKeyTyped
       char karakter = evt.getKeyChar();
       if(!(  (karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)  )){
           evt.consume();
           getToolkit().beep();
       }
    }//GEN-LAST:event_jtuangmukaKeyTyped

    private void jtuangmukaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtuangmukaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == KeyEvent.VK_ENTER){
            getToolkit().beep();
            
            int harga_barang = Integer.parseInt(this.jthargabarang.getText());
            int uang_muka = Integer.parseInt(this.jtuangmuka.getText());
            
            int sisa_harga = harga_barang - uang_muka;
            
            this.jtsisaharga.setText(String.valueOf(sisa_harga));
            this.jtlamanagsuran.requestFocus();
        }
    }//GEN-LAST:event_jtuangmukaKeyPressed

    private void jtkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtkodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar_cicilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar_cicilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar_cicilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar_cicilan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftar_cicilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbbatal;
    public javax.swing.JButton jbcaribarang;
    public javax.swing.JButton jbcaripelanggan;
    public javax.swing.JButton jbhapus;
    public javax.swing.JButton jbsimpan;
    public javax.swing.JButton jbtambah;
    public javax.swing.JButton jbubah;
    public javax.swing.JComboBox<String> jccari;
    public javax.swing.JComboBox<String> jcstatus;
    public com.toedter.calendar.JDateChooser jdtanggaldaftar;
    public javax.swing.JTable jtable;
    public javax.swing.JTextField jtangsuran;
    public javax.swing.JTextField jtcari;
    public javax.swing.JTextField jthargabarang;
    public javax.swing.JTextField jtkode;
    public javax.swing.JTextField jtkodebarang;
    public javax.swing.JTextField jtlamanagsuran;
    public javax.swing.JTextField jtnamabarang;
    public javax.swing.JTextField jtnamapelanggan;
    public javax.swing.JTextField jtnik;
    public javax.swing.JTextField jtsisaharga;
    public javax.swing.JTextField jtuangmuka;
    // End of variables declaration//GEN-END:variables
}
