/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.event.KeyEvent;
import method.method_pelanggan;

/**
 *
 * @author Muhammad Rydwan
 */
public class pelanggan extends javax.swing.JFrame {

    /**
     * Creates new form uang_muka
     */
    public pelanggan() {
        initComponents();
//        this.jtnik.setEnabled(true);
        new method_pelanggan().kunci(this);
        new method_pelanggan().tampil_data(this);
        new method_pelanggan().bersih(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtnik = new javax.swing.JTextField();
        jtnama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jccari = new javax.swing.JComboBox<>();
        jtcari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        jttelepon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtpekerjaan = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtalamat = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jtemail = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtketerangan = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jbbatal = new javax.swing.JButton();
        jbtambah = new javax.swing.JButton();
        jbsimpan = new javax.swing.JButton();
        jbubah = new javax.swing.JButton();
        jbhapus = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel1.setText("Manajemen Pelanggan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("NIK");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Telepon");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jtnik.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtnik.setText("jTextField1");
        jtnik.setNextFocusableComponent(jtnama);
        jtnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtnikActionPerformed(evt);
            }
        });
        jtnik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtnikKeyTyped(evt);
            }
        });
        getContentPane().add(jtnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 220, -1));

        jtnama.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtnama.setText("jTextField2");
        jtnama.setNextFocusableComponent(jttelepon);
        getContentPane().add(jtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 220, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cari");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, -1, -1));

        jccari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jccari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--PILIHAN--", "NIK", "Nama", "Telepon", "Email", "Alamat", "Pekerjaan", "Keterangan" }));
        getContentPane().add(jccari, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 330, 130, -1));

        jtcari.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcariActionPerformed(evt);
            }
        });
        getContentPane().add(jtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(908, 330, 210, -1));

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 1110, 320));

        jttelepon.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jttelepon.setText("jTextField6");
        jttelepon.setNextFocusableComponent(jtemail);
        jttelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtteleponKeyTyped(evt);
            }
        });
        getContentPane().add(jttelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 205, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Pekerjaan");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        jtpekerjaan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtpekerjaan.setText("jTextField8");
        jtpekerjaan.setNextFocusableComponent(jtketerangan);
        getContentPane().add(jtpekerjaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 220, -1));

        jtalamat.setColumns(20);
        jtalamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtalamat.setRows(5);
        jtalamat.setNextFocusableComponent(jtpekerjaan);
        jScrollPane3.setViewportView(jtalamat);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("Email");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jtemail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtemail.setText("jTextField6");
        jtemail.setNextFocusableComponent(jtalamat);
        getContentPane().add(jtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 250, -1));

        jtketerangan.setColumns(20);
        jtketerangan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtketerangan.setRows(5);
        jtketerangan.setNextFocusableComponent(jbsimpan);
        jScrollPane4.setViewportView(jtketerangan);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 310, 120));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("Keterangan Lainnya");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jbbatal.setBackground(new java.awt.Color(221, 48, 6));
        jbbatal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbbatal.setForeground(new java.awt.Color(255, 255, 255));
        jbbatal.setText("Batal");
        jbbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbatalActionPerformed(evt);
            }
        });
        getContentPane().add(jbbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 90, 30));

        jbtambah.setBackground(new java.awt.Color(221, 48, 6));
        jbtambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtambah.setForeground(new java.awt.Color(255, 255, 255));
        jbtambah.setText("Tambah");
        jbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtambahActionPerformed(evt);
            }
        });
        getContentPane().add(jbtambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 90, 30));

        jbsimpan.setBackground(new java.awt.Color(221, 48, 6));
        jbsimpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbsimpan.setForeground(new java.awt.Color(255, 255, 255));
        jbsimpan.setText("Simpan");
        jbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jbsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 90, 40));

        jbubah.setBackground(new java.awt.Color(221, 48, 6));
        jbubah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbubah.setForeground(new java.awt.Color(255, 255, 255));
        jbubah.setText("Ubah");
        jbubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbubahActionPerformed(evt);
            }
        });
        getContentPane().add(jbubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 230, 90, 40));

        jbhapus.setBackground(new java.awt.Color(255, 255, 255));
        jbhapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbhapus.setForeground(new java.awt.Color(255, 51, 51));
        jbhapus.setText("Hapus");
        jbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhapusActionPerformed(evt);
            }
        });
        getContentPane().add(jbhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, 90, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("Alamat");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 90, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/bg-pattern-pelanggan.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbatalActionPerformed
        // TODO add your handling code here:
        new method_pelanggan().kunci(this);
        new method_pelanggan().bersih(this);
        this.jtnik.requestFocus();
    }//GEN-LAST:event_jbbatalActionPerformed

    private void jbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtambahActionPerformed
        // TODO add your handling code here:
        new method_pelanggan().buka_kunci(this);
        
    }//GEN-LAST:event_jbtambahActionPerformed

    private void jbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsimpanActionPerformed
        // TODO add your handling code here:
        new method_pelanggan().simpan(this);
    }//GEN-LAST:event_jbsimpanActionPerformed

    private void jbubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbubahActionPerformed
        // TODO add your handling code here:
        new method_pelanggan().ubah(this);
    }//GEN-LAST:event_jbubahActionPerformed

    private void jbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhapusActionPerformed
        // TODO add your handling code here:
        new method_pelanggan().hapus(this);
    }//GEN-LAST:event_jbhapusActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtnikActionPerformed

    private void jtnikKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtnikKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!( (karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE))){
            evt.consume();
            
        } 
    }//GEN-LAST:event_jtnikKeyTyped

    private void jtteleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtteleponKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if (!( (karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE))){
            evt.consume();
            
        }
    }//GEN-LAST:event_jtteleponKeyTyped

    private void jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMouseClicked
        // TODO add your handling code here:
        new method_pelanggan().klik_table(this);
    }//GEN-LAST:event_jtableMouseClicked

    private void jtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcariActionPerformed
        // TODO add your handling code here:
        new method_pelanggan().cari_data(this);
    }//GEN-LAST:event_jtcariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JButton jbbatal;
    public javax.swing.JButton jbhapus;
    public javax.swing.JButton jbsimpan;
    public javax.swing.JButton jbtambah;
    public javax.swing.JButton jbubah;
    public javax.swing.JComboBox<String> jccari;
    public javax.swing.JTable jtable;
    public javax.swing.JTextArea jtalamat;
    public javax.swing.JTextField jtcari;
    public javax.swing.JTextField jtemail;
    public javax.swing.JTextArea jtketerangan;
    public javax.swing.JTextField jtnama;
    public javax.swing.JTextField jtnik;
    public javax.swing.JTextField jtpekerjaan;
    public javax.swing.JTextField jttelepon;
    // End of variables declaration//GEN-END:variables
}
