/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_tabel;
import form.daftar_cicilan;
import form_detail.detail_barang;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import method_tabel.method_tabel_barang;
/**
 *
 * @author Muhammad Rydwan
 */
public class form_tabel_barang extends javax.swing.JFrame {

    /**
     * Creates new form form_tabel_barang
     */
    public form_tabel_barang() {
        initComponents();
        new method_tabel_barang().tampil_data(this);
    }
    
    detail_barang formDetailBarang = new detail_barang();
    public daftar_cicilan daftarCicilan  = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        jccari = new javax.swing.JComboBox<>();
        jtcari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 157, 500, 400));

        jccari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jccari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--PILIHAN--", "NIK", "Nama", "Telepon", "Email", "Alamat", "Pekerjaan", "Keterangan" }));
        getContentPane().add(jccari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 130, -1));

        jtcari.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcariActionPerformed(evt);
            }
        });
        getContentPane().add(jtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 210, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Daftar Barang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/bg-pattern-tabel-barang.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcariActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtcariActionPerformed

    private void jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMouseClicked
        // TODO add your handling code here:
            int row = jtable.getSelectedRow();
            int pesan = JOptionPane.showConfirmDialog(null, "Lihat Detail Barang yang dipilih?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            
            if (pesan == JOptionPane.YES_OPTION){
                formDetailBarang.formTableBarang = this;
                try {
                    Connection con = new kredit_laptop.Kredit_laptop().getCon();
                    String sql = "SELECT * FROM barang WHERE kd_barang = '"+ this.jtable.getModel().getValueAt(row, 0) +"' ";
                    Statement stat = con.createStatement();
                    ResultSet res = stat.executeQuery(sql);

                    if(res.next()){
                        formDetailBarang.jlkodebarang.setText(res.getString("kd_barang"));
                        formDetailBarang.jlmerk.setText(res.getString("merk"));
                        formDetailBarang.jltipe.setText(res.getString("tipe"));
                        formDetailBarang.jlram.setText(res.getString("ram"));
                        formDetailBarang.jlprosesor.setText(res.getString("prosesor"));
                        formDetailBarang.jlvga.setText(res.getString("vga"));
                        formDetailBarang.jlstorage.setText(res.getString("storage"));
                        formDetailBarang.jlbaterai.setText(res.getString("baterai"));
                        formDetailBarang.jltahunrilis.setText(res.getString("tahun_rilis"));
                        formDetailBarang.jlharga.setText(res.getString("harga"));
                        formDetailBarang.jlstok.setText(res.getString("stok"));
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                formDetailBarang.setVisible(true);
            }else if (pesan == JOptionPane.NO_OPTION){
                daftarCicilan.jtkodebarang.setText(this.jtable.getModel().getValueAt(row, 0).toString());
                String namaBarang = (this.jtable.getModel().getValueAt(row, 1).toString() + " " +  this.jtable.getModel().getValueAt(row, 2).toString());
                daftarCicilan.jtnamabarang.setText(namaBarang);
                daftarCicilan.jthargabarang.setText(this.jtable.getModel().getValueAt(row, 3).toString());
                daftarCicilan.jtuangmuka.requestFocus();
                this.dispose();
            }
            
        
        
        
    }//GEN-LAST:event_jtableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_tabel_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_tabel_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_tabel_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_tabel_barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_tabel_barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JComboBox<String> jccari;
    public javax.swing.JTable jtable;
    public javax.swing.JTextField jtcari;
    // End of variables declaration//GEN-END:variables
}
